name: DSE-VS
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - conda-build
  - numpy
  - matplotlib
  - scipy
  - pandas
  - jupyter
  - control
  - openpyxl
  - pytest
  - pytest-cov
  - poliastro
  - astropy
  - scikit-learn